version: 0.2
   
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Install dependencies needed for running tests
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - echo "STAGE value is $STAGE."
  build:
    commands:
      - |-
        if [ "$STAGE" = 'Dev' ]; then
          npm run build-dev
        elif [ "$STAGE" = 'Qa' ]; then
          npm run build-qa
        else
          npm run build-prod
        fi
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      - mv template-export.yml ./build
      - mv template-configuration.json ./build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'

cache:
  paths:
    - 'node_modules/**/*'